SPECIALISTS = [
    "dentist",
    "cardiologist",
    "dermatologist",
    "orthopedic doctor",
    "gynecologist",
    "neurologist",
    "general physician",
    "physiotherapist",
    "nephrologist",
    "endocrinologist",
    "gastroenterologist",
    "diabetologist",
    "Gediatrics",
    "IVF Center",
    "Weight Loss Center",
]